GET http://localhost:8000/v1/api/users
Content-Type: application/json
Accept: application/json
###
GET http://localhost:8000/v1/ping
Content-Type: application/json
Accept: application/json
###
POST http://localhost:8000/v1/api/users
Content-Type: application/json
Accept: application/json

{
  "firstName" : "dhyslexia first name",
  "lastName" : "dhyslexia last name",
  "username" : "dhyslexia3",
  "email" : "dhyslexia3@gmail.com",
  "password": "password",
  "confPassword": "password"
}